# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  caddy-l4 = {
    pname = "caddy-l4";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "mholt";
      repo = "caddy-l4";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-P6ltBzCQLELDtIQkQ2E3xoNBjCyLvwCoWWztyRoR7ZI=";
    };
  };
  claude-code = {
    pname = "claude-code";
    version = "2.1.202";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.202.tgz";
      sha256 = "sha256-VQAcSsi+yBvAmWcZ0Z5k1mpjjYwRiBTYogNZCyve88A=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "6d3087eedff75a715b40c0e124ba15d2dd7bec28";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "6d3087eedff75a715b40c0e124ba15d2dd7bec28";
      fetchSubmodules = false;
      sha256 = "sha256-5yHuAh9k7rT7rtf3uRaXkiUyYvQE9oaCgzhprLm2mr8=";
    };
    date = "2026-06-16";
  };
  netbird = {
    pname = "netbird";
    version = "v0.74.2";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.74.2";
      fetchSubmodules = true;
      sha256 = "sha256-+BGWZzw6a8Fp8NlhtbX81OA3hCTcQ9r6nLuXTsbXCZ8=";
    };
  };
  oh-my-zsh = {
    pname = "oh-my-zsh";
    version = "51e98fadc9d09b0504ce6964e4008c53e9ac1cbb";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "51e98fadc9d09b0504ce6964e4008c53e9ac1cbb";
      fetchSubmodules = false;
      sha256 = "sha256-9JQUOqFG3Bq8Ki/BMT9pcJSa9+WUPdD8s/SJvRKkHik=";
    };
    date = "2026-07-06";
  };
  openbao = {
    pname = "openbao";
    version = "v2.5.5";
    src = fetchFromGitHub {
      owner = "openbao";
      repo = "openbao";
      rev = "v2.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-75Rm9EGkvUKJ05d55bboPAE+Nm/GLLgH1TqDrExkJO0=";
    };
  };
  remotepc-host = {
    pname = "remotepc-host";
    version = "6.12.0";
    src = fetchurl {
      url = "https://static.remotepc.com/downloads/rpc/310320/remotepc-host.deb";
      sha256 = "sha256-mVDKeUeFba2KtIaVCBdiQ/R/IV/rvtWXox1A+zyPK6c=";
    };
  };
  remotepc-host-pi64 = {
    pname = "remotepc-host-pi64";
    version = "6.10.3";
    src = fetchurl {
      url = "https://static.remotepc.com/downloads/rpc/310320/remotepc-host-pi64.deb";
      sha256 = "sha256-GWudSHJLok4ZnedN2SFZN5+x42NcV6f3GfKPld/mVhA=";
    };
  };
  rustdesk = {
    pname = "rustdesk";
    version = "1.4.9";
    src = fetchFromGitHub {
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "1.4.9";
      fetchSubmodules = true;
      sha256 = "sha256-AnwdIO4TveC48uMioBCvH60xun24ckK420ONSEB9lQI=";
    };
  };
  sops-install-secrets = {
    pname = "sops-install-secrets";
    version = "f1406619a3884cd5c47992a70b8b35c9c0fcb4c9";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "sops-nix";
      rev = "f1406619a3884cd5c47992a70b8b35c9c0fcb4c9";
      fetchSubmodules = false;
      sha256 = "sha256-aCWC8ngycU7OdJrU2+Je3qf+1a2ykuBvpPhZT/9tXMc=";
    };
    date = "2026-07-04";
  };
  vault = {
    pname = "vault";
    version = "v2.0.3";
    src = fetchFromGitHub {
      owner = "hashicorp";
      repo = "vault";
      rev = "v2.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-s6Muogxe+jvre1qZYRiSGTDgMf0+BVsSOwyxF6+Aa2o=";
    };
  };
  vector = {
    pname = "vector";
    version = "vdev-v0.3.4";
    src = fetchFromGitHub {
      owner = "vectordotdev";
      repo = "vector";
      rev = "vdev-v0.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-srsUNEQfls0B5uE3/p+C6njJzyzXu8JuUY4IVIHlFMA=";
    };
  };
  victoriametrics-cluster = {
    pname = "victoriametrics-cluster";
    version = "v1.147.0-cluster";
    src = fetchFromGitHub {
      owner = "VictoriaMetrics";
      repo = "VictoriaMetrics";
      rev = "v1.147.0-cluster";
      fetchSubmodules = false;
      sha256 = "sha256-GVYAW1K0AgEOfjsnI4xDGJyil5yj3kR2ngS1ZtRuWMI=";
    };
  };
  zabbix74 = {
    pname = "zabbix74";
    version = "7.4.11";
    src = fetchFromGitHub {
      owner = "zabbix";
      repo = "zabbix";
      rev = "7.4.11";
      fetchSubmodules = false;
      sha256 = "sha256-i0zWbDI5RAvPfPuWVyz0ZbAbynRwYugupwmShHiNQwQ=";
    };
  };
  zabbix80pre = {
    pname = "zabbix80pre";
    version = "8.0.0beta1";
    src = fetchFromGitHub {
      owner = "zabbix";
      repo = "zabbix";
      rev = "8.0.0beta1";
      fetchSubmodules = false;
      sha256 = "sha256-hEhposPj3CEZt/RSnfuVGsQmvFtWyghfIRi0dygHBKk=";
    };
  };
}
