# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claude-code = {
    pname = "claude-code";
    version = "2.1.139";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.139.tgz";
      sha256 = "sha256-QR4sUA1i1Ap4D0FUt8v50ulQA7zqs2vJn/oXRwT9VrA=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "77c906c0ba56aabdbc72041bf9111b565cdd6171";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "77c906c0ba56aabdbc72041bf9111b565cdd6171";
      fetchSubmodules = false;
      sha256 = "sha256-hwsYgDnby50JNVpTRYlF3UR/Rrpt01OrxVuryF40CFY=";
    };
    date = "2026-02-02";
  };
  netbird = {
    pname = "netbird";
    version = "v0.70.5";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.70.5";
      fetchSubmodules = true;
      sha256 = "sha256-AsM+MEeBqxnwD1jE8ocI93tF3l/7s+s5nF073ZMAi/Y=";
    };
  };
  oh-my-zsh = {
    pname = "oh-my-zsh";
    version = "a07126330b9f56f12f1e00ddd29786d35d6e64d9";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "a07126330b9f56f12f1e00ddd29786d35d6e64d9";
      fetchSubmodules = false;
      sha256 = "sha256-SC57P9UxNBfO9lceSxL0u21/qNOcIjPcMGs2IgPkYDQ=";
    };
    date = "2026-05-11";
  };
  openbao = {
    pname = "openbao";
    version = "v2.5.3";
    src = fetchFromGitHub {
      owner = "openbao";
      repo = "openbao";
      rev = "v2.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-VpW27vWKtqabJiNxuyx3PGDThHF6MOlxxfzD1UksX6I=";
    };
  };
  remotepc-host = {
    pname = "remotepc-host";
    version = "6.10.7";
    src = fetchurl {
      url = "https://download.remotepc.com/downloads/rpc/310320/remotepc-host.deb";
      sha256 = "sha256-raiDEUiYwbWfknxEAEGpVDnTLXOskl3BdbDaWwgSs44=";
    };
  };
  rustdesk = {
    pname = "rustdesk";
    version = "1.4.6";
    src = fetchFromGitHub {
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "1.4.6";
      fetchSubmodules = true;
      sha256 = "sha256-2MZOM+SHDrjFhCIHcFB7zABpwC7hNtS0XNFx2FpaqIE=";
    };
  };
  vault = {
    pname = "vault";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "hashicorp";
      repo = "vault";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-7F5LM9ZxMmj1fob4ZzRoWmEfQMgtbBPaglwxvzFD0FU=";
    };
  };
  vector = {
    pname = "vector";
    version = "v0.55.0";
    src = fetchFromGitHub {
      owner = "vectordotdev";
      repo = "vector";
      rev = "v0.55.0";
      fetchSubmodules = false;
      sha256 = "sha256-1t0fHBYBBfG8oFbo1QPXb5y8+lyIPPve4bDtry+KF5Q=";
    };
  };
  victoriametrics-cluster = {
    pname = "victoriametrics-cluster";
    version = "v1.143.0-cluster";
    src = fetchFromGitHub {
      owner = "VictoriaMetrics";
      repo = "VictoriaMetrics";
      rev = "v1.143.0-cluster";
      fetchSubmodules = false;
      sha256 = "sha256-0qcyxE7jPyl28B/HkhQIXW4vCwJBCk6yNgif7Ms1Ni4=";
    };
  };
  zabbix74 = {
    pname = "zabbix74";
    version = "7.4.10";
    src = fetchFromGitHub {
      owner = "zabbix";
      repo = "zabbix";
      rev = "7.4.10";
      fetchSubmodules = false;
      sha256 = "sha256-ERvjoYLO4meFCPiHK3pfz2dByObbZE9pLQ/kUy3/y/0=";
    };
  };
}
