# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  claude-code = {
    pname = "claude-code";
    version = "2.0.60";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.0.60.tgz";
      sha256 = "sha256-GoT6lxODhokOqaoy7QP/pTdVdQIxDI978dM9GCvaeRQ=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "9c870f63e28ec1e83305f7f6cb73c941e699f74f";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "9c870f63e28ec1e83305f7f6cb73c941e699f74f";
      fetchSubmodules = false;
      sha256 = "sha256-9I2H9x5We6Pl+DBYHjR1s3UT8wgwcpAH03kn9CqtdQc=";
    };
    date = "2025-11-04";
  };
  netbird = {
    pname = "netbird";
    version = "v0.60.7";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.60.7";
      fetchSubmodules = true;
      sha256 = "sha256-ANrLDTvDlSoNDtH4aKzZ6siLAHYT3v3Ivqy2e5di8Jc=";
    };
  };
  oh-my-zsh = {
    pname = "oh-my-zsh";
    version = "a98a9f7122d583a9547e9a8b2ab8c14570fc6e54";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "a98a9f7122d583a9547e9a8b2ab8c14570fc6e54";
      fetchSubmodules = false;
      sha256 = "sha256-leoNUXGNq2WHSzeTsEX0EcazW/Ue0dQCKj+XvnBYneo=";
    };
    date = "2025-12-05";
  };
  rustdesk = {
    pname = "rustdesk";
    version = "1.4.4";
    src = fetchFromGitHub {
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "1.4.4";
      fetchSubmodules = true;
      sha256 = "sha256-o7jsVWiCkHaKFpAu27r/Lr1Q9g7uR/OYJdwsiQeDJUA=";
    };
  };
  vector = {
    pname = "vector";
    version = "v0.51.1";
    src = fetchFromGitHub {
      owner = "vectordotdev";
      repo = "vector";
      rev = "v0.51.1";
      fetchSubmodules = false;
      sha256 = "sha256-EjG8FFz4PDAgCPTkHAxJieW+t6RAPx3MTSku8QGXjYg=";
    };
  };
}
